// <auto-generated />
namespace WebBanHang.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update_EmailInOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_EmailInOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "202312292258552_Update_EmailInOrder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
